<?xml version="1.0"?>
<page id="GLib.test_fail"
      type="topic"
      style="function"
      xmlns="http://projectmallard.org/1.0/"
      xmlns:api="http://projectmallard.org/experimental/api/"
      xmlns:ui="http://projectmallard.org/1.0/ui/">
  <info>
    <link xref="index" group="function" type="guide"/>
    <api:function>
      <api:returns>
        <api:type>void</api:type>
      </api:returns>
      <api:name>g_test_fail</api:name>
    </api:function>
  </info>
  <title>GLib.test_fail</title>
  <synopsis><code mime="text/x-gjs">
function test_fail(): void {
    // Gjs wrapper for g_test_fail()
}
  </code></synopsis>
  <p>Indicates that a test failed. This function can be called
multiple times from the same test. You can use this function
if your test failed in a recoverable way.</p>  <p>Do not use this function if the failure of a test could cause
other tests to malfunction.</p>  <p>Calling this function will not stop the test from running, you
need to return from the test function yourself. So you can
produce additional diagnostic messages or even continue running
the test.</p>  <p>If not called from inside a test, this function does nothing.</p>
  <p>Since 2.30</p>

</page>
